# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: postgres_itskills
    image: postgres
    restart: no
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

      
  adminer:
    image: adminer
    ports:
      - 8080:8080

